package com.run4sky.entities;
// Generated Sep 8, 2018, 3:25:48 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DeviceLocation generated by hbm2java
 */
@Entity
@Table(name = "deviceLocation", catalog = "run4sky_test", uniqueConstraints = @UniqueConstraint(columnNames = "device_id"))
public class DeviceLocation implements java.io.Serializable {

	private Integer id;
	private Device device;
	private String ipExt;
	private String ipInt;

	public DeviceLocation() {
	}

	public DeviceLocation(Device device, String ipExt, String ipInt) {
		this.device = device;
		this.ipExt = ipExt;
		this.ipInt = ipInt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", unique = true)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@Column(name = "ipExt", length = 100)
	public String getIpExt() {
		return this.ipExt;
	}

	public void setIpExt(String ipExt) {
		this.ipExt = ipExt;
	}

	@Column(name = "ipInt", length = 100)
	public String getIpInt() {
		return this.ipInt;
	}

	public void setIpInt(String ipInt) {
		this.ipInt = ipInt;
	}

}
