package com.run4sky.entities;
// Generated Sep 8, 2018, 3:25:48 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DeviceType generated by hbm2java
 */
@Entity
@Table(name = "deviceType", catalog = "run4sky_test", uniqueConstraints = @UniqueConstraint(columnNames = "type"))
public class DeviceType implements java.io.Serializable {

	private String type;
	private Set devices = new HashSet(0);

	public DeviceType() {
	}

	public DeviceType(String type) {
		this.type = type;
	}

	public DeviceType(String type, Set devices) {
		this.type = type;
		this.devices = devices;
	}

	@Id

	@Column(name = "type", unique = true, length = 200)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceType")
	public Set getDevices() {
		return this.devices;
	}

	public void setDevices(Set devices) {
		this.devices = devices;
	}

}
