package com.run4sky.entities;
// Generated Sep 8, 2018, 3:25:48 PM by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "device", catalog = "run4sky_test", uniqueConstraints = @UniqueConstraint(columnNames = "mac"))
public class Device implements java.io.Serializable {

	private Integer id;
	private DeviceType deviceType;
	private String mac;
	private String cpuName;
	private String ram;
	private String os;
	private Integer cpuQtd;
	private boolean isRegistered;
	private Set deviceLocations = new HashSet(0);

	public Device() {
	}

	public Device(DeviceType deviceType, String mac, String cpuName, String ram, String os, Integer cpuQtd,
			boolean isRegistered, Set deviceLocations) {
		this.deviceType = deviceType;
		this.mac = mac;
		this.cpuName = cpuName;
		this.ram = ram;
		this.os = os;
		this.cpuQtd = cpuQtd;
		this.isRegistered = isRegistered;
		this.deviceLocations = deviceLocations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_type")
	public DeviceType getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(DeviceType deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "mac", unique = true, length = 17)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	@Column(name = "cpuName", length = 300)
	public String getCpuName() {
		return this.cpuName;
	}

	public void setCpuName(String cpuName) {
		this.cpuName = cpuName;
	}

	@Column(name = "ram", length = 300)
	public String getRam() {
		return this.ram;
	}

	public void setRam(String ram) {
		this.ram = ram;
	}

	@Column(name = "os", length = 300)
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Column(name = "cpuQtd")
	public Integer getCpuQtd() {
		return this.cpuQtd;
	}

	public void setCpuQtd(Integer cpuQtd) {
		this.cpuQtd = cpuQtd;
	}

	@Column(name = "isRegistered", length = 1)
	public boolean getIsRegistered() {
		return this.isRegistered;
	}

	public void setIsRegistered(boolean isRegistered) {
		this.isRegistered = isRegistered;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "device")
	public Set getDeviceLocations() {
		return this.deviceLocations;
	}

	public void setDeviceLocations(Set deviceLocations) {
		this.deviceLocations = deviceLocations;
	}

}
