package com.run4sky.beans;
// Generated Sep 8, 2018, 3:45:43 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "Client", catalog = "Ximds_EvilCorp")
public class Client implements java.io.Serializable {

	private int id;
	private String name;
	private String description;

	public Client() {
	}

	public Client(int id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", nullable = false, length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
