package com.run4sky.beans;
// Generated Sep 8, 2018, 7:30:52 PM by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ConnectionLogs generated by hbm2java
 */
@Entity
@Table(name = "connectionLogs", catalog = "Ximds_EvilCorp")
public class ConnectionLogs implements java.io.Serializable {

	private Integer id;
	private String mac;
	private LocalDateTime connectionTime;
	private long durationConnection;

	public ConnectionLogs() {
	}

	public ConnectionLogs(LocalDateTime connectionTime) {
		this.connectionTime = connectionTime;
	}

	public ConnectionLogs(String mac, LocalDateTime connectionTime, long durationConnection) {
		this.mac = mac;
		this.connectionTime = connectionTime;
		this.durationConnection = durationConnection;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mac", length = 300)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	//@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "connectionTime", nullable = false, length = 19)
	public LocalDateTime getConnectionTime() {
		return this.connectionTime;
	}

	public void setConnectionTime(LocalDateTime connectionTime) {
		this.connectionTime = connectionTime;
	}

	@Column(name = "durationConnection", length = 16777215)
	public long getDurationConnection() {
		return this.durationConnection;
	}

	public void setDurationConnection(long durationConnection) {
		this.durationConnection = durationConnection;
	}

}
