package com.run4sky.beans;
// Generated Sep 1, 2018, 8:04:03 PM by Hibernate Tools 5.2.11.Final

import java.time.LocalDateTime;


/**
 * ConnectionLogs generated by hbm2java
 */
public class ConnectionLogs implements java.io.Serializable {

	private int id;
	private String mac;
	private LocalDateTime connectionTime;

	public ConnectionLogs() {
	}

	public ConnectionLogs(int id, LocalDateTime connectionTime) {
		this.id = id;
		this.connectionTime = connectionTime;
	}

	public ConnectionLogs(int id, String deviceType, LocalDateTime connectionTime) {
		this.id = id;
		this.mac = deviceType;
		this.connectionTime = connectionTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String deviceType) {
		this.mac = deviceType;
	}

	public LocalDateTime getConnectionTime() {
		return this.connectionTime;
	}

	public void setConnectionTime(LocalDateTime connectionTime) {
		this.connectionTime = connectionTime;
	}

}
