package com.run4sky.beans;
// Generated Sep 2, 2018, 11:32:32 PM by Hibernate Tools 5.2.11.Final

import java.time.LocalDateTime;

/**
 * ConnectionLogs generated by hbm2java
 */
public class ConnectionLogs implements java.io.Serializable {

	private Integer id;
	private String mac;
	private LocalDateTime connectionTime;
	private Long durationConnection;

	public ConnectionLogs() {
	}

	public ConnectionLogs(LocalDateTime connectionTime) {
		this.connectionTime = connectionTime;
	}

	public ConnectionLogs(String mac, LocalDateTime connectionTime, Long durationConnection) {
		this.mac = mac;
		this.connectionTime = connectionTime;
		this.durationConnection = durationConnection;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public LocalDateTime getConnectionTime() {
		return this.connectionTime;
	}

	public void setConnectionTime(LocalDateTime connectionTime) {
		this.connectionTime = connectionTime;
	}

	public Long getDurationConnection() {
		return this.durationConnection;
	}

	public void setDurationConnection(Long durationConnection) {
		this.durationConnection = durationConnection;
	}

}
