package com.run4sky.beans;
// Generated 03-ago-2018 14:17:12 by Hibernate Tools 5.2.11.Final

/**
 * DispLocation generated by hbm2java
 */
public class DispLocation implements java.io.Serializable {

	private int id;
	private int dispId;
	private String ip;

	public DispLocation() {
	}

	public DispLocation(int id, int dispId, String ip) {
		this.id = id;
		this.dispId = dispId;
		this.ip = ip;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getDispId() {
		return this.dispId;
	}

	public void setDispId(int dispId) {
		this.dispId = dispId;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
