package com.run4sky.beans;
// Generated 14-ago-2018 13:52:35 by Hibernate Tools 5.2.11.Final

/**
 * InsernalService generated by hbm2java
 */
public class InsernalService implements java.io.Serializable {

	private int id;
	private String mac;
	private String cpu;
	private String ram;
	private String so;
	private int ncpu;

	public InsernalService() {
	}

	public InsernalService(int id, String mac, String cpu, String ram, String so, int ncpu) {
		this.id = id;
		this.mac = mac;
		this.cpu = cpu;
		this.ram = ram;
		this.so = so;
		this.ncpu = ncpu;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public String getCpu() {
		return this.cpu;
	}

	public void setCpu(String cpu) {
		this.cpu = cpu;
	}

	public String getRam() {
		return this.ram;
	}

	public void setRam(String ram) {
		this.ram = ram;
	}

	public String getSo() {
		return this.so;
	}

	public void setSo(String so) {
		this.so = so;
	}

	public int getNcpu() {
		return this.ncpu;
	}

	public void setNcpu(int ncpu) {
		this.ncpu = ncpu;
	}

}
