package com.run4sky.beans1;
// Generated Sep 8, 2018, 3:45:43 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClientLocation generated by hbm2java
 */
@Entity
@Table(name = "ClientLocation", catalog = "Ximds_EvilCorp")
public class ClientLocation implements java.io.Serializable {

	private int id;
	private String clientIpint;
	private String clientIpext;
	private int clientId;

	public ClientLocation() {
	}

	public ClientLocation(int id, String clientIpint, String clientIpext, int clientId) {
		this.id = id;
		this.clientIpint = clientIpint;
		this.clientIpext = clientIpext;
		this.clientId = clientId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CLientIPInt", nullable = false, length = 300)
	public String getClientIpint() {
		return this.clientIpint;
	}

	public void setClientIpint(String clientIpint) {
		this.clientIpint = clientIpint;
	}

	@Column(name = "ClientIPExt", nullable = false, length = 300)
	public String getClientIpext() {
		return this.clientIpext;
	}

	public void setClientIpext(String clientIpext) {
		this.clientIpext = clientIpext;
	}

	@Column(name = "ClientID", nullable = false)
	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

}
