package com.run4sky.beans1;
// Generated Sep 8, 2018, 3:45:43 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConnectionLogs generated by hbm2java
 */
@Entity
@Table(name = "connectionLogs", catalog = "Ximds_EvilCorp")
public class ConnectionLogs implements java.io.Serializable {

	private Integer id;
	private String mac;
	private Date connectionTime;
	private String durationConnection;

	public ConnectionLogs() {
	}

	public ConnectionLogs(Date connectionTime) {
		this.connectionTime = connectionTime;
	}

	public ConnectionLogs(String mac, Date connectionTime, String durationConnection) {
		this.mac = mac;
		this.connectionTime = connectionTime;
		this.durationConnection = durationConnection;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mac", length = 300)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "connectionTime", nullable = false, length = 19)
	public Date getConnectionTime() {
		return this.connectionTime;
	}

	public void setConnectionTime(Date connectionTime) {
		this.connectionTime = connectionTime;
	}

	@Column(name = "durationConnection", length = 16777215)
	public String getDurationConnection() {
		return this.durationConnection;
	}

	public void setDurationConnection(String durationConnection) {
		this.durationConnection = durationConnection;
	}

}
